### ISSUE TITLE
Web Version of DevToys

### ISSUE THREAD

**Issue by Chetan11-dev** [reeseovine/webtoys#17]
I Made an Open Source Web Version of https://webtoys.ovine.xyz/ accessible at https://www.omkar.cloud/devtools/.
Repo: https://github.com/omkarcloud/devtools
![Screenshot (528)](https://github.com/veler/DevToys/assets/53407137/bc91c82c-d17b-4209-8742-11acb472b171)
Thought would be useful to you to serve as Code Inspiration.

**Comment by reeseovine** [comment]
looks cool! this didn't need to be an issue though, i have discussions enabled 😅
